spring:
  application:
    name: agent-server

server:
  address: localhost
  port: 8080

# reasoner type can be chosen among "hermit", "pellet" and "jfact"
reasoner:
  type: hermit

# ontology filename in the directory "resources"
ontology:
<<<<<<< HEAD
  filename: ontology_v4.owl
=======
  filename: sometimesyoutry.rdf
>>>>>>> 8214b33ed5d97a2813fae5c82cff3b0281e6db2f

eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.address}:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    ipAddress: ${server.address}
    instanceId: ${server.address}:${server.port}