spring:
  application:
    name: agent-server

server:
  address: localhost
  port: 8080

# reasoner type can be chosen among "hermit", "pellet" and "jfact"
reasoner:
  type: pellet

# ontology filename in the directory "resources"
ontology:
  filename: ontology.owl

eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.address}:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    ipAddress: ${server.address}
    instanceId: ${server.address}:${server.port}